[package]
name = "xinto"
version = "0.2.0"
authors = ["Guillaume Valadon <guillaume@valadon.net>"]
edition = "2018"

[dependencies]
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
